### ISSUE TITLE
Add demo on codesandbox.io?

### ISSUE THREAD

**Issue by cowchimp** [SamyPesse/react-combo-keys#3]
Is it possible to link to a demo from the Readme?
Will help to understand the value proposition and usage.
Thanks

**Comment by butlersrepos** [comment]
Here's a demo of using the simpler `<ComboKey/>` tag to navigate and activate some buttons, hope it isn't too contrived.

https://codesandbox.io/s/p96mok35wm

**Comment by cowchimp** [comment]
fantastic. thank you.
